register(GRAMPLET,
         id = "Aviopaikat",
         name = _("Aviopaikat"),
         description = _("Aviopaikat"),
         status = STABLE,
         version = '0.0.9',
         gramps_target_version = '5.0',
         fname = "Aviopaikat.py",
         gramplet = 'Aviopaikat',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("Aviopaikat"),
         help_url="Aviopaikat gramplet",
         include_in_listing = True,
         navtypes=["Event"],
        )
