register(GRAMPLET,
         id = "SetPlaceProperties",
         name = _("SetPlaceProperties"),
         description = _("Gramplet to set properties for multiple places"),
         status = STABLE,
         version = '0.0.9',
         gramps_target_version = '5.0',
         fname = "SetPlaceProperties.py",
         gramplet = 'SetPlaceProperties',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("SetPlaceProperties"),
         help_url="SetPlaceProperties Gramplet",
         include_in_listing = True,
         navtypes=["Place"],
        )
